"""add total snapshot colunms for user table

Revision ID: 0f15fd477d52
Revises: 30b6995fd92b
Create Date: 2026-05-05 02:09:09.220310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f15fd477d52'
down_revision: Union[str, Sequence[str], None] = '30b6995fd92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column('total_followers', sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        'users',
        sa.Column('total_following', sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        'users',
        sa.Column('total_posts', sa.Integer(), nullable=False, server_default="0")
    )

    op.alter_column('users', 'total_followers', server_default=None)
    op.alter_column('users', 'total_following', server_default=None)
    op.alter_column('users', 'total_posts', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_posts')
    op.drop_column('users', 'total_following')
    op.drop_column('users', 'total_followers')
    # ### end Alembic commands ###
